apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-probe
  labels:
    app: nginx-probe

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-probe

  template:
    metadata:
      labels:
        app: nginx-probe
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /wrongpath
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
